import type {NextPage} from 'next'
import Head from 'next/head'
import {Box, Button, Flex, Icon} from "@chakra-ui/react";
import {MapRoadTwo, PictureOne, Right} from "@icon-park/react";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Flex alignItems={"center"} justifyContent={"center"} width={"100vw"} height={"100vh"}>
        <Flex alignItems={"center"} padding={20} maxWidth={"500px"} width={"100%"} backgroundColor={"gray.50"}>
          <Flex flexDirection={"column"} gap={5} width={"100%"} maxWidth={"300px"}>
            <Link href={"/raster"} passHref>
              <Button leftIcon={<Icon as={PictureOne}/>}
                      rightIcon={<Icon as={Right} marginRight={-10} marginLeft={10}/>} backgroundColor={"gray.200"}
                      as={"a"}>
                Raster Tiles
              </Button>
            </Link>
            <Link href={"/vector"} passHref>
              <Button leftIcon={<Icon as={MapRoadTwo}/>}
                      rightIcon={<Icon as={Right} marginRight={-10} marginLeft={10}/>} backgroundColor={"gray.200"}
                      as={"a"}>
                Vector Tiles
              </Button>
            </Link>
          </Flex>
        </Flex>
      </Flex>
    </>
  )
}

export default Home
